// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHd6BL1i--UomUYKgSIZmyMy_0lAthyTE',
    appId: '1:850659271910:ios:3293ac47cb492cedb20727',
    messagingSenderId: '343659267573',
    projectId: 'world-of-creators-373712',
    authDomain: 'workbefy-5559b.firebaseapp.com',
    storageBucket: 'world-of-creators-373712.appspot.com',
    measurementId: 'G-J8TR8PGJDC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDC8yqzoZwlV0-iTRALl9xN9tmXkRji7ok',
    appId: '1:548685969164:android:2f2c2c8d2fcbdf68e1bb29',
    messagingSenderId: '38599781120',
    projectId: 'gas-station-customer',
    storageBucket: 'gas-station-customer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHd6BL1i--UomUYKgSIZmyMy_0lAthyTE',
    appId: '1:850659271910:ios:3293ac47cb492cedb20727',
    messagingSenderId: '38599781120',
    projectId: 'world-of-creators-373712',
    storageBucket: 'world-of-creators-373712.appspot.com',
    androidClientId: '850659271910-801mgnec3bkmqcqeehb7jhk83psgd4um.apps.googleusercontent.com',
    iosClientId: '850659271910-6pk1rln10cbhmsde00pivq9o1qqutqlk.apps.googleusercontent.com',
    iosBundleId: 'com.cw.worldofcreaters',
  );
}
